<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRMKnx9N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRMKnx9N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRMKnx9N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRMKnx9N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRMKnx9N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RMKnx9N',
    'container.build_id' => 'e74332fb',
    'container.build_time' => 1581171426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRMKnx9N');
