<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP5Iue6N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP5Iue6N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP5Iue6N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP5Iue6N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP5Iue6N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'P5Iue6N',
    'container.build_id' => 'dfc26ad9',
    'container.build_time' => 1581117715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP5Iue6N');
